# Generated by Django 3.0.3 on 2020-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sypmtoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=30)),
                ('img', models.ImageField(null=True, upload_to='app/images')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Sypmtoms',
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(blank=True, max_length=30, null=True)),
                ('recover', models.CharField(blank=True, max_length=30, null=True)),
                ('death', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
